[colors.primary]
background = '#121318'
foreground = '#e2e2e9'
 
[colors.cursor]
text = '#e2e2e9'
cursor = '#c5c6d0' 
 
[colors.vi_mode_cursor]
text = '#121318'
cursor = '#b0c6ff' 
 
[colors.search.matches]
foreground = '#44464f' 
background = '#e0bbdd' 
 
[colors.search.focused_match]
foreground = '#44464f' 
background = '#b0c6ff' 
 
[colors.footer_bar]
foreground = '#44464f' 
background = '#e2e2e9' 
 
[colors.hints.start]
foreground = '#44464f' 
background = '#c0c6dc' 
 
[colors.hints.end]
foreground = '#44464f' 
background = '#c0c6dc' 
 
[colors.selection]
text = '#121318'
background = '#b0c6ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#b0c6ff' 
yellow = '#475d92' 
blue = '#b0c6ff' 
magenta = '#e0bbdd' 
cyan = '#c0c6dc' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
